# Generated by Django 3.2.18 on 2023-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
